{
    "application": False,
    "author": "Nedas Zilinskas",
    "auto_install": False,
    "category": "Website",
    "contributors": "Nedas Zilinskas",
    "currency": "EUR",
    "data": [
        "data/x_attachment_group.xml",
        "data/product_product.xml",
        "data/ir_attachment.xml",
        "data/ir_actions_server.xml",
        "security/ir.model.access.csv",
        "views/assets.xml",
        "views/templates.xml",
        "views/snippets.xml",
        "views/ir_attachment.xml",
        "views/product_template.xml",
        "views/x_attachment_group.xml",
    ],
    "demo": [],
    "depends": ["website_sale"],
    "description": "Allow to download categorized attachments on website",
    "external_dependencies": [],
    "images": ["static/description/main_screenshot.png"],
    "installable": True,
    "license": "AGPL-3",
    "live_test_url": "http://minilini.com/page/start",
    "maintainer": "Nedas Zilinskas",
    "name": "Attachments Building Block",
    "price": 25.0,
    "qweb": [],
    "summary": "Allow to download categorized attachments on website",
    "support": "nedas.zilinskas@gmail.com",
    "version": "14.0.1.0.0",
    "website": "http://nedaszilinskas.com",
}
