{
    'name': 'Restrict Product Creation | Disable Quick Product Creation',
    'version': "14.1.1.1",
    'sequence': 1,    
    "summary": """Restrict Product Creation in sale, purchase. customer invoice and vendor bill""",
    "description": """
    """,
    'email': 'apps@maisolutionsllc.com',
    'website':'http://maisolutionsllc.com/',
    'summary': 'Restrict Product Creation in sale, purchase. customer invoice and vendor bill',
    'author': 'MAISOLUTIONSLLC',
    'category': 'product',
    'depends': ['sale', 'account', 'purchase'],
    'data': [
             'views/purchase.xml',
             'views/sale.xml',
             'views/invoice.xml',
             ],
    'price': 7,
    'currency': 'EUR',
    'license': 'OPL-1',
    'auto_install': True,
    'installable': True,
    'application':False,
    "images": ['static/description/main_screenshot.png'],
}
